# Lefthook configuration
# See https://github.com/evilmartians/lefthook/blob/master/docs/configuration.md

pre-commit:
  parallel: true
  commands:
    rubocop:
      glob: "*.{rb,rake}"
      run: bundle exec rubocop --force-exclusion {staged_files}
      stage_fixed: true
